const banksData = {
  sberbank: {
    name: 'Сбербанк',
    filename: 'sberbank',
    sum: 30,
    rate: 8,
    term: 30,
    contribution: 25,
  },
  'alfa-bank': {
    name: 'Альфа-Банк',
    filename: 'alfa-bank',
    sum: 2,
    rate: 12,
    term: 5,
    contribution: 10,
  },
  tinkoff: {
    name: 'Тинькофф',
    filename: 'tinkoff',
    sum: 15,
    rate: 8,
    term: 15,
    contribution: 10,
  },
  vtb: {
    name: 'ВТБ',
    filename: 'vtb',
    sum: 16.3,
    rate: 7,
    term: 7,
    contribution: 0,
  },
  'dom.rf': {
    name: 'ДОМ.РФ',
    filename: 'dom.rf',
    sum: 30,
    rate: 6.1,
    term: 30,
    contribution: 20,
  },
  'loko-bank': {
    name: 'ЛокоБанк',
    filename: 'loko-bank',
    sum: 7,
    rate: 6.5,
    term: 7,
    contribution: 0,
  },
  'credit-europe-bank': {
    name: 'Сredit Europe Bank',
    filename: 'credit-europe-bank',
    sum: 6,
    rate: 13.99,
    term: 10,
    contribution: 10,
  },
  'post-bank': {
    name: 'Почта Банк',
    filename: 'post-bank',
    sum: 5,
    rate: 4.9,
    term: 7,
    contribution: 10,
  },
};

export default banksData;
